# ./.air.toml
root = "."
tmp_dir = "tmp"

[build]
  # Este comando ahora funciona porque el módulo está bien definido
  cmd = "go build -buildvcs=false -o ./tmp/main ./app"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "resources", "database"]

[log]
  time = true