services: # Producción
  # Base de Datos PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database/schema:/docker-entrypoint-initdb.d
    restart: always

  # Aplicación
  app:
    build:
      context: .
      target: production
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable"
      MEILI_URL: "http://meilisearch:7700"
      MEILI_MASTER_KEY: "${MEILI_KEY}"
    env_file:
      - .env
    restart: always

  # Motor de búsqueda MeiliSearch
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: "${MEILI_KEY}"
    restart: always
